### ISSUE TITLE
create_archive(): enforce files exist within root?

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#101]
In the docstring of `create_archive()` we state:

![image](https://user-images.githubusercontent.com/10383417/234843188-5bd2be59-dbc7-4761-89e6-a1a1353dc3a2.png)

But there are no checks that the files are relative paths and exist below `root`. 

This can have probably undesired side-effects, e.g.:

```python
with tempfile.TemporaryDirectory() as tmp:
    file = audeer.touch(f'{tmp}/a')
    audeer.create_archive('.', file, 'a.zip')
```

This includes a file from a temporary folder outside the working directory and when the archive is unpacked creates it within the working directory:

```python
files = audeer.extract_archive(
    'a.zip',
    '.',
)
print(files)
```
```
['tmp/tmpx7hnjy3m/a']
```

I wonder if we need checks that ensure that `files` are relative paths (also not leading outside the root directory) or at least exist within root.

**Comment by hagenw** [comment]
Yes, we should forbid to access files outside of `root`
