### ISSUE TITLE
Revert change of audeer.extract_archive() return value under Windows?

### ISSUE THREAD

**Issue by hagenw** [audeering/audeer#109]
We changed the returned paths of `audeer.extract_archive()` under Windows to return paths using the Windows file separator instead of the Linux file separator (as part of https://github.com/audeering/audeer/pull/103). This was a breaking change and let a lot of our packages fail under Windows, e.g. with `audb` 1.5.0 in https://github.com/audeering/audbcards/pull/18.

The change was also not documented in the CHANGELOG.

I'm wondering if we should release a bug fix release that reverts this change?

If not then we should at least do a bug fix release updating the CHANGELOG.

**Comment by Bahaabrougui** [comment]
As we're already under a stable release and this is a breaking change, I vote to revert it to the way it was before. Unless there is a specific reason for changing the return paths that we'll impact things in the future in a positive way ?

**Comment by hagenw** [comment]
I think the main reason we changed it was that we considered it to be a bug as other functions like `audeer.list_file_names()` do return the path as `a\b` under Windows instead of `a/b`.

But I agree that we have a lot of code that is based on the behavior as it was before, so fixing this bug after such a long time might indeed not be a good idea.

**Comment by Bahaabrougui** [comment]
Ah I see then it's a compromise we have to make, unless we find that it's enough to fix this in just one package (e.g. `audb`) rather than updating multiple ones, in that case we can go for fix if it makes sense.

**Comment by frankenjoe** [comment]
I would consider it a bug before and would not revert the change.

**Comment by frankenjoe** [comment]
> If not then we should at least do a bug fix release updating the CHANGELOG.

Yes, that we should do of course.
