### ISSUE TITLE
audeer.path() is slow

### ISSUE THREAD

**Issue by hagenw** [audeering/audeer#131]
As discussed in https://github.com/audeering/audiofile/pull/141 calling `audeer.path()` on a huge number of files might be much slower as a user expects. The main reason is that it calls `os.path.realpath()` that converts symbolic links to actual paths, which needs a file operation when executed. If we would replace this by `os.path.abspath()` it would be much faster.

I see two options:

1.) Change the current behavior and introduce breaking changes for symbolic links
2.) Add an option to disable symbolic link checking, so we can use this in other libraries, but do not introduce breaking changes directly to `audeer`

**Comment by hagenw** [comment]
From https://docs.python.org/3/library/os.path.html

![image](https://github.com/audeering/audeer/assets/173624/9788f7e2-d53b-4453-998e-88394283c798)

**Comment by frankenjoe** [comment]
> 2.) Add an option to disable symbolic link checking, so we can use this in other libraries, but do not introduce breaking changes directly to audeer

Do you see any package were we can actually ever rule that symbolic links are used? Probably we will always need to leave this decision to the user, so maybe we could add `audeer.config.support_symbolic_links` or alike?

**Comment by hagenw** [comment]
My idea was more that in packages for which we know that they are used on lots of files, we simply set the argument to not expand symbolic links and add a comment to the docstring that users have to take care of it themselves. E.g. I think of packages like `audiofile`, `auglib`, `audb`.

**Comment by frankenjoe** [comment]
Sounds a bit dangerous too me. But maybe we should first check if we can limit the calls to `audeer.path()`where it is really necessary (similar to how you did it with `audfile`). E.g. in `audb` it should be sufficient to call it once on the cache root folder since everything inside that folder we create and therefore we know it cannot contain symbolic links. I guess the same applies to `auglib`, where we also have a cache folder and everything inside that folder cannot be symbolic.

**Comment by hagenw** [comment]
It's true, `audb` and `auglib` should be possible to improve (if needed, maybe we do it already like you propose?).
I think the most problematic case is indeed `audiofile`. There we could add an option to `audeer.path()` to ignore symbolic links, or we simply leave `audeer.path()` as it is and instead no longer use it inside `audiofile`.
