### ISSUE TITLE
Use replace_symlink instead of follow_symlink in audeer.path()?

### ISSUE THREAD

**Issue by hagenw** [audeering/audeer#134]
In https://github.com/audeering/audeer/pull/132 we have introduced the `follow_symlink` argument to `audeer.path()`.
If set to `False` it does return the symlink path and not the actual path, e.g.

```python
import audeer
import numpy as np
import os
import soundfile

signal = np.ones((8000,))
soundfile.write("file.wav", signal, 8000)
os.symlink("file.wav", "link.wav")
```
then we get
```python
>>> os.path.basename(audeer.path("link.wav"))
'file.wav'
>>> os.path.basename(audeer.path("link.wav", follow_symlink=False))
'link.wav'
```

But when using with another application, a user might worry that `follow_symlink=False` means that the original file is not loaded:

```python
path = audeer.path("link.wav", follow_symlink=False)
signal, sampling_rate = soundfile.read(path)
```

The worry is not needed, as the file is loaded.
So maybe `replace_symlink` would be a better name?

**Comment by hagenw** [comment]
@frankenjoe maybe I'm overthinking this, and `follow_symlink` is just fine?
When comparing to [follow_symlinks](https://docs.python.org/3/library/os.html#follow-symlinks) in `os`, they seem to use the name for what we are doing here.

**Comment by frankenjoe** [comment]
When introducing it I trying to come up with alternative name as usually I prefer to have an option set to `False` by default. But I couldn't really come up with something better and it makes a lot of sense to stick to the name they also use in `os`.
