### ISSUE TITLE
audeer.move() works only for files on the same file system

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#144]
I run into `OSError: [Errno 18] Invalid cross-device link` when I used `audeer.move()` to move a file to another file system. Under the hood we call `os.rename()`, which indeed does not support moving between file systems:

![image](https://github.com/audeering/audeer/assets/10383417/1a8c3c81-bf93-43ff-b6d4-30f5933beb77)

So I guess we should either document it or - if possible - use `shutil.move()` when files are not on the same file system.

**Comment by frankenjoe** [comment]
I guess the easiest workaround is to capture `OSError` and check if error message contains `'Invalid cross-device link'`. If this is the case we fallback to `shutil.move()`.

**Comment by hagenw** [comment]
This is a duplicate of https://github.com/audeering/audeer/issues/71, where you actually proposed more or less the same solution to solve the issue. So maybe it's time we tackle this ;)

**Comment by frankenjoe** [comment]
Duplicate of #71
