### ISSUE TITLE
Support long file path on Windows

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#15]
In order to support long file paths on Windows `safe_path` should prepend `\\\\?\\`.

**Comment by hagenw** [comment]
@chausner-audeering this tries to fix problems with long paths in `audb` under Windwos (https://github.com/audeering/audb/issues/35).

As it should be easy to [enable support for long file paths on Windows](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later), and this is also enabled per default for the Windows 2019 and 2022 runners on Github, I'm wondering if it is still worth the effort to support it?

**Comment by hagenw** [comment]
We are in principle able to fix and test this (see https://github.com/audeering/audeer/pull/65), but it would also mean that for long paths the returned path string will always look like
```
\\?\C:\Users\...
```
instead of
```
C:\Users\...
```

Don't know if this will lead to other problems then.

**Comment by chausner-audeering** [comment]
> As it should be easy to [enable support for long file paths on Windows](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later), and this is also enabled per default for the Windows 2019 and 2022 runners on Github, I'm wondering if it is still worth the effort to support it?

If I am not mistaken, these two things go hand-in-hand, i.e. long file paths have to be enabled on Windows and the `\\?\` path prefix must be used.

**Comment by hagenw** [comment]
> > As it should be easy to [enable support for long file paths on Windows](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later), and this is also enabled per default for the Windows 2019 and 2022 runners on Github, I'm wondering if it is still worth the effort to support it?
> 
> If I am not mistaken, these two things go hand-in-hand, i.e. long file paths have to be enabled on Windows and the `\\?\` path prefix must be used.

No, if long file support is enabled it just works without adding `\\?\`. If long file support is disabled with:

```
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 0 -PropertyType DWORD -Force
```
we need to add `//?/` to make it work.

**Comment by chausner-audeering** [comment]
I see. I just thought that enabling the registry setting alone didn't work in all cases in the past but I am not fully sure. We can try without and if we run into any issues bring it back.

**Comment by hagenw** [comment]
I will close this for now.

If the problem happens again, we can reopen and have a look at the solution proposed in https://github.com/audeering/audeer/pull/65
