### ISSUE TITLE
Combine safe_path with os.path.join

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#18]
In my code I have a lot of these statements:

```
path = audeer.safe_path(os.path.join('/root',  'sub', 'my.txt'))
```

would be nice if I could simply do:

```
path = audeer.safe_path('/root',  'sub', 'my.txt')
```

**Comment by hagenw** [comment]
In my opinion the purpose of `audeer.safe_path` and `os.path.join` is completely different.

I see the point that we are using them together quite often. But instead changing `audeer.safe_path`, I would rather add something like `audeer.join_path()` instead to combine them.

**Comment by frankenjoe** [comment]
I'm fine with both solutions.
