### ISSUE TITLE
Function to create archive

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#19]
Since we have `extract_archive()`, maybe we should also add a `create_archive()` function.

**Comment by hagenw** [comment]
Would you restrict that to ZIP, or also allow for TAR.GZ and ZIP?

**Comment by frankenjoe** [comment]
Good question. If it's not too complicated, it makes sense to support the same formats `extract_archive()` can extract, but at the moment it would also be ok to support only `ZIP`.
