### ISSUE TITLE
Naming of git related functions

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#29]
Now we have `git_tags()` and `version_from_git()`. Maybe we should unify them, e.g. by renaming the latter to `git_version()`?

**Comment by hagenw** [comment]
Good question. It seems to make sense to unify them.

Why I haven't choosen `git_version()` in the first place was that it sounds like we are asking for the version of git itself.
To avoid this we would then have to rename `git_tags()` to `tags_from_git()` which is not so nice.

**Comment by frankenjoe** [comment]
What about `git_repo_version()` and `git_repo_tags()`?
