### ISSUE TITLE
Default value of num_workers in run_tasks

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#41]
Currently the default value of `num_workers` in `run_tasks()` is `None`, which defaults to 5 times the number of CPUs on the machine. I wonder if it would be safer to change the default value to a smaller number or maybe even 1. We recently had the case where we forgot to overwrite the default value and spammed our compute server.

**Comment by hagenw** [comment]
Yes, I agree.
It's better to set it to `1` as it will not hurt.
