### ISSUE TITLE
audeer.common_directory() is not working for macOS

### ISSUE THREAD

**Issue by hagenw** [audeering/audeer#46]
In https://github.com/audeering/audeer/pull/44 I added tests for macOS, but they fail for `audeer.common_directoy()`:
https://github.com/audeering/audeer/pull/44/checks?check_run_id=2718638791

**Comment by frankenjoe** [comment]
Tricky one. It seems that `audeer.safe_path()` is adding an additional `/System/Volumes/Data` to the file path, similar to Windows adding `C:\` e.g.
