### ISSUE TITLE
audeer.list_file_names() ignores hidden files

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#66]
As the following example shows `audeer.list_file_names()` does not return hidden files, but `audeer.list_dir_names()` does.

```python
with tempfile.TemporaryDirectory() as root:
    audeer.touch(audeer.path(root, 'file'))
    audeer.touch(audeer.path(root, '.file'))
    audeer.mkdir(audeer.path(root, 'folder'))
    audeer.mkdir(audeer.path(root, '.folder'))
    files = audeer.list_file_names(root, basenames=True)
    print(files)
    dirs = audeer.list_dir_names(root, basenames=True)
    print(dirs)
```
```
['file']
['.folder', 'folder']
```

**Comment by frankenjoe** [comment]
Seems to be related to `glob.glob()`, which we are using in `audeer.list_file_names()` but not `audeer.list_dir_names()`. From the docu:

![image](https://user-images.githubusercontent.com/10383417/162275822-544a58a7-b9cf-43df-98ab-75d4d9ec1e5a.png)

**Comment by hagenw** [comment]
Great, thanks for spotting this. A little bit unfortunate that we have different behavior for folders and files, but I would indeed continue with this as you proposed in #67 for backward compatibility.

**Comment by frankenjoe** [comment]
Yes, it's unfortunate. We could deprecate the default value for `2.0.0` if we think the behavior should be consistent at some point.
