### ISSUE TITLE
Replace with empty file extension

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audeer#87]
When we replace with an empty extension we currently get:

```python
>>> import audeer
>>> file = 'foo.bar'
>>> audeer.replace_file_extension(file, '')
'foo.'
>>> audeer.replace_file_extension(file, '', ext='.bar')
'foo.'
>>> audeer.replace_file_extension(file, '', ext='bar')
'foo.'
```

I wonder if makes more sense if we remove the '.' in that case?

**Comment by hagenw** [comment]
I guess yes, as you would expect to don't have a `.` when you remove the file extension.

**Comment by hagenw** [comment]
We now remove the `'.'` which makes sense, so I will close here.
